### ISSUE TITLE
Menu usuario

### ISSUE THREAD

**Issue by favarcar** [favarcar/sipardnna-main#1]
Inhabilitar los select de tipo doc y ciudad al momento de ver el usuario como rol 3 de consulta.

**Comment by favarcar** [comment]
Adicional a esto, en la ciudad siempre se muestra TUNJA al abrir el perfil del usuario, debe mostrar la ciudad a la que pertenece el mismo.

**Comment by andreaguva** [comment]
Ya esta hecho el cambio
