### ISSUE TITLE
Creación de menu para adminsitrador

### ISSUE THREAD

**Issue by favarcar** [favarcar/sipardnna-main#2]
Crear un menu para el administrador de la plataforma, donde se permita: 
1. La gestión de usuarios, creación de los mismos, edición de contraseñas, cambio de roles.
2. Gestión de listas que se utilicen en los demás formularios que cuenten con una entidad (tabla)  en la base de datos, debe permitir un CRUD para cada uno.

**Comment by andreaguva** [comment]
Cambios realizados
